language: python
env:
  global:
    - PYTHONASYNCIODEBUG='1'
    - PIPENV_IGNORE_VIRTUALENVS=1

python:
  - "3.6"

install:
  - pip install codecov
  - pip install pipenv && pipenv install --system --deploy --dev

script:
  - make tests

after_success:
  - codecov
